apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-deployment
  labels:
    app: ctse-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ctse-app
  template:
    metadata:
      labels:
        app: ctse-app
    spec:
      containers:
      - name: offer-app
        image: minolirathnayake/offermanagement:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000