apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers-deployment
  labels:
    app: ctse-app
spec:
  replicas: 3 #number of instances in pods
  selector:
    matchLabels:
      app: ctse-app # This must match the labels set on the pod
  template:
    metadata:
      labels:
        app: ctse-app # set labels on the pod
    spec:
      containers:
      - name: offer-app
        image: minolirathnayake/offermanagement:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000